describe('Verify register scenario', () => {
  it('Failed Register Empty Fields', () => {
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#register-button').should('be.visible').click()
    cy.get(':nth-child(3) > .field-validation-error > span').should('contain.text','Last name is required.')
    cy.get(':nth-child(4) > .field-validation-error > span').should('contain.text','Email is required.')
  })
  it('Failed Register using Existing Email', () => {
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#gender-male')
    .should('be.visible')
    .click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('elvanisa')
    cy.get('#LastName')
    .should('be.visible')
    .type('muhsina')
    cy.get('#Email')
    .should('be.visible')
    .type('elva@gmail.com')
    cy.get('#Password')
    .should('be.visible')
    .type('Password12345')
    cy.get('#ConfirmPassword').should('be.visible').type('Password12345')
    cy.get('#register-button').should('be.visible').click()
    cy.get('.validation-summary-errors > ul > li').should('contain.text', 'The specified email already exists')
  })
  it('Sucess Register', () => {
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#gender-male')
    .should('be.visible')
    .click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('elvanisa')
    cy.get('#LastName')
    .should('be.visible')
    .type('muhsina')
    cy.get('#Email')
    .should('be.visible')
    .type(`${Date.now()}@gmail.com`)
    cy.get('#Password')
    .should('be.visible')
    .type('Password12345')
    cy.get('#ConfirmPassword').should('be.visible').type('Password12345')
    cy.get('#register-button').should('be.visible').click()
    cy.get('.result').should('be.visible').contains('Your registration completed')
  })
})